from tile_server.config import AppConfig


def minimal_config(**overrides):
    values = {
        "role": "test",
        "render_database_url": "postgresql://render:secret@postgres:5432/gis",
        "import_database_url": "postgresql://import:secret@postgres:5432/gis",
        "control_database_url": None,
        "database_admin_url": None,
        "tile_store": "filesystem",
        "tile_fs_path": "/tmp/tiles",
        "s3": None,
        "map_version": "default",
        "default_layer": "default",
        "style_xml": None,
        "style_workdir": "/tmp/tile-style",
        "map_bundle_uri": None,
        "admin_enabled": False,
        "admin_token": None,
        "listen_host": "127.0.0.1",
        "listen_port": 8080,
        "worker_poll_interval": 0.1,
        "worker_batch_size": 8,
        "worker_id": None,
        "metatile_size": 8,
        "store_full_metatile": True,
        "threads": 4,
        "import_threads": 4,
        "render_worker_processes": 1,
        "render_backend": "python-mapnik",
        "render_backend_url": None,
        "osm2pgsql_extra_args": "",
        "import_source_mode": "local",
        "allow_internal_import_downloads": False,
        "allow_public_import_downloads": False,
        "import_staging_path": "/tmp/tile-imports",
        "external_data_mode": "auto",
        "allow_internal_external_data_downloads": False,
        "allow_public_external_data_downloads": False,
        "external_data_staging_path": "/tmp/tile-external-data",
        "bundle_output_dir": "/tmp/tile-bundles",
        "allow_network_fetch": False,
        "dry_run": True,
    }
    values.update(overrides)
    return AppConfig(**values)
