apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tile-server.fullname" . }}-secrets
type: Opaque
stringData:
  RENDER_DATABASE_URL: {{ .Values.database.renderUrl | quote }}
  CONTROL_DATABASE_URL: {{ .Values.database.controlUrl | quote }}
  IMPORT_DATABASE_URL: {{ .Values.database.importUrl | quote }}
  ADMIN_TOKEN: {{ .Values.admin.token | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.tileStore.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.tileStore.s3.secretAccessKey | quote }}
