apiVersion: v1
kind: Service
metadata:
  name: {{ include "tile-server.fullname" . }}-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tile-server.fullname" . }}-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: 8080
